FROM python:3.10.4-alpine3.15

LABEL maintainer="sjjctl@protonmail.com"

RUN pip install \
    autopep8==1.6.0 \
    bandit==1.7.4 \
    black==22.3.0 \
    doc8==0.11.1 \
    coverage==6.3.2 \
    flake8==4.0.1 \
    isort==5.10.1 \
    mypy==0.950 \
    pylint==2.13.9 \
    pytest==7.1.2 \
    requests-mock==1.9.3 \
    yamllint==1.26.3
